# Site settings
title: Carlos Alarcon
description: Nothing learns better than experience
keywords: Modern, Blogging, Fun
author: jchuerva
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
